{ config, pkgs, ... }:

{
  imports = [
    ./hardware-configuration.nix
    ./users.nix
  ];

  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/sda";

  time.timeZone = "UTC";

  # we always want git and vim
  environment.systemPackages = with pkgs; [
    cloud-init
    git
    glibc
    python3
    vim
  ];

  environment.etc = {
    "cloud/cloud.cfg.d/99_pve.cfg" = {
      text = "datasource_list: [ NoCloud, ConfigDrive, None ]";
      mode = "0644";
    };

    # This doesn't do anything since systemd services are manually generated by NixOS.
    "cloud/cloud-init.disabled" = {
      text = "";
      mode = "0644";
    };
  };

  # https://github.com/NixOS/nixpkgs/pull/47664
  networking.usePredictableInterfaceNames = false;

  services.cloud-init = {
    enable = true;
    ext4.enable = true;
    network.enable = true;
    settings = {
      users = [ "default" ];
      disable_root = true;
      system_info = {
        distro = "nixos";
        network = {
          renderers = [ "networkd" ];
        };
        default_user = {
          name = "nixos";
          lock_passwd = true;
          groups = [ "wheel" ];
          sudo = [ "ALL=(ALL) NOPASSWD:ALL" ];
        };
      };
    };
  };

  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = false;
    settings.KbdInteractiveAuthentication = false;
  };

  services.qemuGuest.enable = true;

  system.stateVersion = "23.05";
}
